### ISSUE TITLE
'npm install' fails

### ISSUE THREAD

**Issue by SwikarBhattarai** [espinacs/ant-design-boilerplate#7]
![image](https://user-images.githubusercontent.com/36293831/54139500-cb8fa180-4449-11e9-8531-1ed6455ec09b.png)

**Comment by etorhub** [comment]
Hi,

Although is not happening to me, I've just updated some dependencies and fixed some vulnerabilities.

Let me know if it still happens, and it that case please indicate something more about your PC configuration (node version, etc)

**Comment by etorhub** [comment]
So, 3 weeks later with no answer, i'm closing this issue.
